export const USER_SIGNED_IN = 'USER_SIGNED_IN';
export const USER_SIGNED_IN_RESET = 'USER_SIGNED_IN_RESET';

export const USER_SIGNED_UP = 'USER_SIGNED_UP';
export const USER_SIGNED_UP_RESET = 'USER_SIGNED_UP_RESET';

export const USER_SIGNED_OUT = 'USER_SIGNED_OUT';
export const USER_SIGNED_OUT_RESET = 'USER_SIGNED_OUT_RESET';
