export const ROOM_SUBJECTS_REQUEST = 'ROOM_SUBJECTS_REQUEST';
export const ROOM_SUBJECTS_SUCCESS = 'ROOM_SUBJECTS_SUCCESS';
export const ROOM_SUBJECTS_FAIL = 'ROOM_SUBJECTS_FAIL';

export const CREATE_SUBJECT_REQUEST = 'CREATE_SUBJECT_REQUEST';
export const CREATE_SUBJECT_SUCCESS = 'CREATE_SUBJECT_SUCCESS';
export const CREATE_SUBJECT_FAIL = 'CREATE_SUBJECT_FAIL';
export const CREATE_SUBJECT_RESET = 'CREATE_SUBJECT_RESET';