export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_FAIL = 'USER_SIGNUP_FAIL';
export const USER_SIGNUP_RESET = 'USER_SIGNUP_RESET';

export const USER_STATUS_REQUEST = 'USER_STATUS_REQUEST';
export const USER_STATUS_SUCCESS = 'USER_STATUS_SUCCESS';
export const USER_STATUS_FAIL = 'USER_STATUS_FAIL';

export const USER_SIGN_IN_REQUEST = 'USER_SIGN_IN_REQUEST';
export const USER_SIGN_IN_SUCCESS = 'USER_SIGN_IN_SUCCESS';
export const USER_SIGN_IN_FAIL = 'USER_SIGN_IN_FAIL';
export const USER_SIGN_IN_RESET = 'USER_SIGN_IN_RESET';

export const USER_SIGN_OUT_REQUEST = 'USER_SIGN_OUT_REQUEST';
export const USER_SIGN_OUT_SUCCESS = 'USER_SIGN_OUT_SUCCESS';
export const USER_SIGN_OUT_FAIL = 'USER_SIGN_OUT_FAIL';

export const USER_GOOGLE_REQUEST = 'USER_GOOGLE_REQUEST';
export const USER_GOOGLE_SUCCESS = 'USER_GOOGLE_SUCCESS';
export const USER_GOOGLE_FAIL = 'USER_GOOGLE_FAIL';

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL';